Ext.define('Checkers.store.BoardStore', {
    extend: 'Ext.data.Store',
    requires: ['Checkers.model.Square'],
    config: {
        storeID: 'BoardStore',
        model: 'Checkers.model.Square',
        fields: [
            {name: 'squareID', type: 'string'},
            {name: 'occupied', type: 'string'}
        ],
        data : [
            {squareID: '1A', occupied: 'none', background: 'light'},
            {squareID: '2A', occupied: 'none', background: 'dark'},
            {squareID: '3A', occupied: 'none', background: 'light'},
            {squareID: '4A', occupied: 'none', background: 'dark'},
            {squareID: '5A', occupied: 'none', background: 'light'},
            {squareID: '6A', occupied: 'none', background: 'dark'},
            {squareID: '7A', occupied: 'none', background: 'light'},
            {squareID: '8A', occupied: 'none', background: 'dark'},
            {squareID: '1B', occupied: 'none', background: 'dark'},
            {squareID: '2B', occupied: 'none', background: 'light'},
            {squareID: '3B', occupied: 'none', background: 'dark'},
            {squareID: '4B', occupied: 'none', background: 'light'},
            {squareID: '5B', occupied: 'none', background: 'dark'},
            {squareID: '6B', occupied: 'none', background: 'light'},
            {squareID: '7B', occupied: 'none', background: 'dark'},
            {squareID: '8B', occupied: 'none', background: 'light'},
            {squareID: '1C', occupied: 'none', background: 'light'},
            {squareID: '2C', occupied: 'none', background: 'dark'},
            {squareID: '3C', occupied: 'none', background: 'light'},
            {squareID: '4C', occupied: 'none', background: 'dark'},
            {squareID: '5C', occupied: 'none', background: 'light'},
            {squareID: '6C', occupied: 'none', background: 'dark'},
            {squareID: '7C', occupied: 'none', background: 'light'},
            {squareID: '8C', occupied: 'none', background: 'dark'},
            {squareID: '1D', occupied: 'none', background: 'dark'},
            {squareID: '2D', occupied: 'none', background: 'light'},
            {squareID: '3D', occupied: 'none', background: 'dark'},
            {squareID: '4D', occupied: 'none', background: 'light'},
            {squareID: '5D', occupied: 'none', background: 'dark'},
            {squareID: '6D', occupied: 'none', background: 'light'},
            {squareID: '7D', occupied: 'none', background: 'dark'},
            {squareID: '8D', occupied: 'none', background: 'light'},
            {squareID: '1E', occupied: 'none', background: 'light'},
            {squareID: '2E', occupied: 'none', background: 'dark'},
            {squareID: '3E', occupied: 'none', background: 'light'},
            {squareID: '4E', occupied: 'none', background: 'dark'},
            {squareID: '5E', occupied: 'none', background: 'light'},
            {squareID: '6E', occupied: 'none', background: 'dark'},
            {squareID: '7E', occupied: 'none', background: 'light'},
            {squareID: '8E', occupied: 'none', background: 'dark'},
            {squareID: '1F', occupied: 'none', background: 'dark'},
            {squareID: '2F', occupied: 'none', background: 'light'},
            {squareID: '3F', occupied: 'none', background: 'dark'},
            {squareID: '4F', occupied: 'none', background: 'light'},
            {squareID: '5F', occupied: 'none', background: 'dark'},
            {squareID: '6F', occupied: 'none', background: 'light'},
            {squareID: '7F', occupied: 'none', background: 'dark'},
            {squareID: '8F', occupied: 'none', background: 'light'},
            {squareID: '1G', occupied: 'none', background: 'light'},
            {squareID: '2G', occupied: 'none', background: 'dark'},
            {squareID: '3G', occupied: 'none', background: 'light'},
            {squareID: '4G', occupied: 'none', background: 'dark'},
            {squareID: '5G', occupied: 'none', background: 'light'},
            {squareID: '6G', occupied: 'none', background: 'dark'},
            {squareID: '7G', occupied: 'none', background: 'light'},
            {squareID: '8G', occupied: 'none', background: 'dark'},
            {squareID: '1H', occupied: 'none', background: 'dark'},
            {squareID: '2H', occupied: 'none', background: 'light'},
            {squareID: '3H', occupied: 'none', background: 'dark'},
            {squareID: '4H', occupied: 'none', background: 'light'},
            {squareID: '5H', occupied: 'none', background: 'dark'},
            {squareID: '6H', occupied: 'none', background: 'light'},
            {squareID: '7H', occupied: 'none', background: 'dark'},
            {squareID: '8H', occupied: 'none', background: 'light'}
        ],
        autoLoad: true
    }
});