Ext.define('Checkers.store.BoardStore', {
    extend: 'Ext.data.Store',
    requires: ['Checkers.model.Square'],
    config: {
        storeID: 'BoardStore',
        model: 'Checkers.model.Square',
        data : [
            {squareID: 'A1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'B1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'C1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'D1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'E1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'F1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'G1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'H1', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'A2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'B2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'C2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'D2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'E2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'F2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'G2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'H2', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'A3', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'B3', occupiedBy: 'black', pieceType: 'King', decoration: '', background: 'dark'},
            {squareID: 'C3', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'D3', occupiedBy: 'black', pieceType: 'Piece', decoration: '', background: 'dark'},
            {squareID: 'E3', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'F3', occupiedBy: 'black', pieceType: 'Piece', decoration: '', background: 'dark'},
            {squareID: 'G3', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'H3', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'A4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'B4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'C4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'D4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'E4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'F4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'G4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'H4', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'A5', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'B5', occupiedBy: 'black', pieceType: 'King', decoration: '', background: 'dark'},
            {squareID: 'C5', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'D5', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'E5', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'F5', occupiedBy: 'black', pieceType: 'Piece', decoration: '', background: 'dark'},
            {squareID: 'G5', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'H5', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'A6', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'B6', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'C6', occupiedBy: 'red', pieceType: 'Piece', decoration: '', background: 'dark'},
            {squareID: 'D6', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'E6', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'F6', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'G6', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'H6', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'A7', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'B7', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'C7', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'D7', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'E7', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'F7', occupiedBy: 'black', pieceType: 'Piece', decoration: '', background: 'dark'},
            {squareID: 'G7', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'H7', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'A8', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'B8', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'C8', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'dark'},
            {squareID: 'D8', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'E8', occupiedBy: 'red', pieceType: 'Piece', decoration: '', background: 'dark'},
            {squareID: 'F8', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'},
            {squareID: 'G8', occupiedBy: 'red', pieceType: 'King', decoration: '', background: 'dark'},
            {squareID: 'H8', occupiedBy: 'none', pieceType: 'none', decoration: '', background: 'light'}
        ],
        autoLoad: true
    }
});
